<img height="180px" src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" align="left" hspace="30px" vspace="50px"/>

# Welcome to your next notebook with SDA!

During the classes we will mostly use [Google Colaboratory](https://colab.research.google.com/?hl=en) which is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud.

However, for bigger projects, especially involving Deep Learning and/or big data reading, it might be a better choice to setup Jupyter Notebook or Jupyter Lab on your computer. Also, it is worth noticing that there is a great number of useful extensions (see [nbextensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/index.html) and [jupyter-labextension](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html)) not available for Colab users.

<img src="https://drive.google.com/uc?export=view&id=1UO2urRciECzoKE_vHy4RMGfFbkOWOGlW" alt="SDA logo" align="left" width="100px" hspace="10px" vspace="10px"/>
<br>

# TASKS

<img src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" width="150" align='right'/>
<br>

## Linear Algebra

### **<font color='#306998'>TASKS </font><font color='#ffd33b'>1.1 - 1.10</font>** should be already completed :)

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.11</font>**

For the matrix from task 1.7:
* calculate its determinant,
* calculate its trace (the sum of elements on the main diagonal),
* find the largest and smallest item.

$$
A=
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16
\end{bmatrix}
$$

In [1]:
import numpy as np
A = np.arange(1, 17).reshape(4, 4)

In [2]:
np.linalg.det(A)

0.0

In [3]:
A.max()

16

In [4]:
A.diagonal().sum()

34

In [5]:
A.min()

1

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.12</font>**

Define two `3x3` real matrices, ie. whose elements consist entirely of real numbers. For the first matrix, draw the numbers from standard normal (Gaussian) distribution, ie. $\mu = 0$ and $\sigma = 1$. For the second one, set the standard devation to 1 and mean value to 5.

**See Appendix.**

Next, for each of them:
* multiply all elements by a scalar 10,
* extract the element in the middle,
* transpose them
* get its trace & sum of all elements

and calculate their:
* sum
* difference
* element-wise multiplication result
* element-wise division result
* matrix product (matrix multiplication)

In [6]:
B = np.random.normal(size=9).reshape(3,3)
B

array([[ 0.77956589, -0.37650047, -0.99851772],
       [-1.50714022, -0.08127186,  0.09624256],
       [ 0.61841571,  0.12619647, -0.49811218]])

In [7]:
C = np.random.normal(loc=5, scale=1, size=9).reshape(3, 3)
C

array([[6.46361148, 4.24768971, 3.60221012],
       [4.82116415, 3.42609771, 4.33935509],
       [4.33440242, 4.58057429, 4.57658111]])

In [8]:
B * 10

array([[  7.79565887,  -3.76500469,  -9.98517723],
       [-15.07140221,  -0.81271863,   0.9624256 ],
       [  6.18415706,   1.26196467,  -4.98112184]])

In [9]:
C * 10

array([[64.63611483, 42.47689714, 36.02210119],
       [48.21164146, 34.26097708, 43.39355094],
       [43.34402424, 45.8057429 , 45.76581113]])

In [10]:
B[1,1]

-0.08127186335536067

In [11]:
C[C.shape[0]//2,C.shape[1]//2]

3.426097707878402

In [12]:
B.T

array([[ 0.77956589, -1.50714022,  0.61841571],
       [-0.37650047, -0.08127186,  0.12619647],
       [-0.99851772,  0.09624256, -0.49811218]])

In [13]:
C.T

array([[6.46361148, 4.82116415, 4.33440242],
       [4.24768971, 3.42609771, 4.58057429],
       [3.60221012, 4.33935509, 4.57658111]])

In [14]:
B.trace()

0.20018183970854303

In [15]:
C.trace()

14.466290304294258

In [16]:
B + C

array([[7.24317737, 3.87118924, 2.6036924 ],
       [3.31402393, 3.34482584, 4.43559765],
       [4.95281813, 4.70677076, 4.07846893]])

In [17]:
B - C

array([[-5.6840456 , -4.62419018, -4.60072784],
       [-6.32830437, -3.50736957, -4.24311253],
       [-3.71598672, -4.45437782, -5.0746933 ]])

In [18]:
B * C

array([[ 5.03881102, -1.59925717, -3.59687065],
       [-7.2661704 , -0.27844534,  0.41763064],
       [ 2.68046253,  0.57805229, -2.27965081]])

In [19]:
B / C

array([[ 0.12060841, -0.08863653, -0.27719586],
       [-0.31260919, -0.02372141,  0.022179  ],
       [ 0.14267612,  0.02755036, -0.10883937]])

In [20]:
np.matmul(B, C)

array([[-1.10433718, -2.55235801, -3.39540646],
       [-9.71623984, -6.23946316, -5.34124134],
       [ 2.44659408,  0.77755959,  0.49562378]])

In [21]:
B @ C

array([[-1.10433718, -2.55235801, -3.39540646],
       [-9.71623984, -6.23946316, -5.34124134],
       [ 2.44659408,  0.77755959,  0.49562378]])

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.14</font>**

Create an array with the following elements: `[23, 45, 124, 112, 150, 43, 25, 17, 268, 254, 95, 97, 8]` and filter out the ones that are less than or equal to their mean value. How many such numbers are there?

In [22]:
A = np.array([[23, 45, 124, 112, 150, 43, 25, 17, 268, 254, 95, 97, 8]])
meanA = A.mean()
meanA

97.0

In [23]:
less_mean = A[A <= meanA]

In [24]:
less_mean, len(less_mean)

(array([23, 45, 43, 25, 17, 95, 97,  8]), 8)

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.15</font>**

Use the array defined above to evaluate mean value and standard deviation. Check how many of these numbers is within a distance of at most one standard deviation from the mean, ie. belongs to the closed interval `[mean - std, mean + std]`.

In [25]:
std = A.std()
std

82.3958550115048

In [26]:
B = A[(A >= (meanA - std)) & (A < (meanA + std))]

In [27]:
B, len(B)

(array([ 23,  45, 124, 112, 150,  43,  25,  17,  95,  97]), 10)

Write a function `get_sum_of_squared_naturals()` that takes one argument as an input (call it `max_value`) and returns the sum of squared natural numbers `k` such that $k \leq max\_value.$

Make sure that the input given by a user is a natural number. Set the default value to 5.

In [28]:
def get_sum_of_squared_naturals(k):
  n = abs(int(k))
  if k == n and k != 0:
    arr = np.arange(k + 1)
    arr = np.square(arr)
    sum_arr = arr.sum()
    return sum_arr
  else:
    arr = np.arange(6)
    arr = np.square(arr)
    sum_arr = arr.sum()
    return f"{k} is not a natural number. Calculation was done for k = 5, {sum_arr}"

In [29]:
get_sum_of_squared_naturals(3)

14

In [30]:
get_sum_of_squared_naturals(-4.5)

'-4.5 is not a natural number. Calculation was done for k = 5, 55'

In [31]:
get_sum_of_squared_naturals(0)

'0 is not a natural number. Calculation was done for k = 5, 55'

In [32]:
get_sum_of_squared_naturals(1/17)

'0.058823529411764705 is not a natural number. Calculation was done for k = 5, 55'

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.17</font>**

Create the following 4x4 matrix 4x4, and then:
* print out an element from the second row and the third column (starting from 1),
* check which element is equal to 0,
* with array indexing:
    * display element equal to 3,
    * view vector `[3, 11, 0]`,
* calculate its:
    * determinant,
    * trace (sum of diagonal entries),
    * the maximum and mininum elements,
    * the mean value of each column,
    * the maximum value of each row,
* find its transposition and multiply both matrices mathematically, ie. get the product of $A \cdot A^T,$
* determine its eigenvalues and eigenvectors. (optional)

```
np.array([
    [1, 15, 4, 13],
    [8, 21, 3, 12],
    [11, 13, 11, 5],
    [32, 13, 0, 2]
])
```

In [33]:
C = np.array([[1,15,4,13],[8,21,3,12],[11,13,11,5],[32,13,0,2]])
C

array([[ 1, 15,  4, 13],
       [ 8, 21,  3, 12],
       [11, 13, 11,  5],
       [32, 13,  0,  2]])

In [34]:
C[1, 2]

3

In [35]:
np.where(C == 0)

(array([3], dtype=int64), array([2], dtype=int64))

In [36]:
np.where(C == 3)

(array([1], dtype=int64), array([2], dtype=int64))

In [37]:
C[1:,2:3]

array([[ 3],
       [11],
       [ 0]])

In [38]:
np.linalg.det(C)

-19963.99999999999

In [39]:
C.diagonal().sum()

35

In [40]:
C.min(), C.max()

(0, 32)

In [41]:
meancol1 = C[:,:1].mean()
meancol1

13.0

In [42]:
meancol2 = C[:,1:2].mean()
meancol2

15.5

In [43]:
meancol3 = C[:,2:3].mean()
meancol3

4.5

In [44]:
meancol4 = C[:,3:].mean()
meancol4

8.0

In [45]:
maxrow1 = C[:1,].max()
maxrow1

15

In [46]:
maxrow2 = C[1:2,].max()
maxrow2

21

In [47]:
maxrow3 = C[2:3,].max()
maxrow3

13

In [48]:
maxrow4 = C[3:,].max()
maxrow4

32

In [49]:
CT = C.T
CT

array([[ 1,  8, 11, 32],
       [15, 21, 13, 13],
       [ 4,  3, 11,  0],
       [13, 12,  5,  2]])

In [50]:
C * CT

array([[  1, 120,  44, 416],
       [120, 441,  39, 156],
       [ 44,  39, 121,   0],
       [416, 156,   0,   4]])

In [51]:
from numpy import linalg as LA

In [52]:
eigenvalues, eigenvectors = LA.eig(C)

In [53]:
eigenvalues

array([ 41.24366578, -18.12008708,   3.01436162,   8.86205968])

In [54]:
eigenvectors

array([[-0.42552168, -0.46858888, -0.27614717,  0.02912145],
       [-0.55379568, -0.17594186,  0.6248671 , -0.13789778],
       [-0.48050507,  0.10806928, -0.19647432,  0.98203903],
       [-0.53043051,  0.858947  , -0.70333611, -0.12544114]])

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.18</font>**

Create a 3x3 array and normalize its columns, ie. scale the values such that sum of each column equals 1 (unit vectors).

In [55]:
D = np.random.rand(3,3)
D

array([[0.88429395, 0.98470838, 0.46366913],
       [0.32621509, 0.33509343, 0.08121595],
       [0.27735936, 0.97408241, 0.03097488]])

In [56]:
normalized_arr = D/D.sum(axis=0,keepdims=1)
normalized_arr

array([[0.59433613, 0.42927554, 0.80517689],
       [0.21924996, 0.14608123, 0.14103419],
       [0.18641391, 0.42464323, 0.05378892]])

In [57]:
normalized_arr.sum(0)

array([1., 1., 1.])

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.19</font>**

Write a function that accepts a positive natural number $p\in\mathbb{N}_1$ and two NumPy vectors as an input (both of the same shape). The function should return the Mikowski distance between those vectors, ie.:
$$d_p(X, Y) = \left(\sum_{i=1}^n |x_i - y_i|^p\right)^\frac{1}{p},$$

where $X=[x_1, x_2, ..., x_n]\in\mathbb{R}^n$ and $Y=[y_1, y_2, ..., y_n]\in\mathbb{R}^n.$

*Hint: you can use the following assertions `assert a.size == b.size, "Arrays must be of the same shape"`, and `assert isinstance(input_array_1, np.ndarray)`.*

In [58]:
def mikowski_distance(a, b, p=2):
  assert a.size == b.size, "Arrays must be of the same shape"
  assert isinstance(a, np.ndarray), f"First input is not array"
  assert isinstance(b, np.ndarray), f"Second input is not array"
  return np.sum(np.abs(a - b)**p)**(1/p)

In [59]:
mikowski_distance(np.array([[1,2],[3,4]]), np.array([[2,3],[5,6]]))

3.1622776601683795

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.20</font>**

Determine the length of the following vectors using Euclidean norm:
* $v_1=[0, 5]$
* $v_2=[0, -3]$
* $v_3=[7, 0]$
* $v_4=[-\pi, 0]$
* $v_5=[3, -4]$
* $v_6=[1, 7]$
* $v_7=[5\sqrt{3}, -3, 4]$
* $v_8=[1, 2, 3, 4]$

*Hint: using default parameters of `numpy.linalg.norm()` function will return Frobenius norm for matrices which is equivalent to Euclidean norm for vectors:*
https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html

In [60]:
import numpy as np

In [61]:
vectors = [
    np.array([0,5]),
    np.array([0,-3]),
    np.array([7,0]),
    np.array([-np.pi,0]),
    np.array([3,-4]),
    np.array([1,7]),
    np.array([np.sqrt(3)*5,-3,4]),
    np.array([1,2,3,4]),
]

In [62]:
for vector in vectors:
  print(np.linalg.norm(vector))

5.0
3.0
7.0
3.141592653589793
5.0
7.0710678118654755
10.0
5.477225575051661


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.21</font>**

For the following vectors `a=[3, -2]` and `b=[-2, -3]`, determine their scalar product and the angle between these vectors.

*Correct answer $\alpha = 90^\circ$.*

In [63]:
a = np.array([3, -2])
b = np.array([-2, -3])

In [64]:
dot_product_ab = np.dot(a, b)

In [65]:
euclidean_norm_a = np.linalg.norm(a)

In [66]:
euclidean_norm_b = np.linalg.norm(b)

In [67]:
denominator = euclidean_norm_a * euclidean_norm_b

In [68]:
cos_gamma = dot_product_ab / denominator
gamma = np.arccos(cos_gamma)

In [69]:
cos_gamma, gamma

(0.0, 1.5707963267948966)

In [70]:
np.degrees(gamma)

90.0

In [71]:
np.rad2deg(gamma)

90.0

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.22</font>**

For the following vectors `a=[0, 3]` and `b=[2, 2]`, determine their scalar product and the angle between these vectors.

*Correct answer $\alpha = 45^\circ$.*

In [72]:
a = np.array([0,3])
b = np.array([2,2])

In [73]:
dot_product_ab = np.dot(a, b)

In [74]:
euclidean_norm_a = np.linalg.norm(a)
euclidean_norm_b = np.linalg.norm(b)
denominator = euclidean_norm_a * euclidean_norm_b

In [75]:
cos_gamma = dot_product_ab / denominator
gamma = np.arccos(cos_gamma)

In [76]:
np.degrees(gamma)

45.00000000000001

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.23</font>**

For the following vectors `a=[3, -2]` and `b=[1, 7]`, determine their scalar product and the angle between these vectors.

*Correct answer $\alpha ≈ 116^\circ$.*

In [77]:
a = np.array([3,-2])
b = np.array([1,7])

In [78]:
dot_product_ab = np.dot(a, b)

In [79]:
euclidean_norm_a = np.linalg.norm(a)
euclidean_norm_b = np.linalg.norm(b)
denominator = euclidean_norm_a * euclidean_norm_b

In [80]:
cos_gamma = dot_product_ab / denominator
gamma = np.arccos(cos_gamma)

In [81]:
np.degrees(gamma)

115.55996517182382

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.24</font>**

Normalize each vector from Task 20.

In [82]:
for vector in vectors:
  print(vector / np.linalg.norm(vector))

[0. 1.]
[ 0. -1.]
[1. 0.]
[-1.  0.]
[ 0.6 -0.8]
[0.14142136 0.98994949]
[ 0.8660254 -0.3        0.4      ]
[0.18257419 0.36514837 0.54772256 0.73029674]


<img src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" width="150" align='right'/>
<br>

## Appendix: random numbers generators

1. Randomly generated number(s) from normal (Gauss) distribution.
```python
np.random.normal()
np.random.normal(size=6)
```
1. Randomly selected numbers from the uniform system.
```python
np.random.uniform(size=6)
```
1. Randomly selected number from a specific range.
```python
np.random.randint(3, 30, size=6)
```
1. Randomly selected floating-point number
```python
np.random.random()
```