In [1]:
import numpy as np

1. Utwórz trójwymiarową tablicę z jedynkami na przekątnej i zerami w innych miejscach.

In [2]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

2. Utwórz tablicę liczb 3x2 wypełnioną jedynkami.

In [3]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

3. Utwórz macierz o kształcie 2x5, wypełnioną szóstkami.

In [4]:
a = np.zeros((2,5)) + 6
print(a)

[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


4. Utwórz wektor 5, 13, 21, 29, ..., 101

In [5]:
np.arange(5, 102, 8)

array([  5,  13,  21,  29,  37,  45,  53,  61,  69,  77,  85,  93, 101])

5. Utwórz tablicę 1-D składającą się z 20 równomiernie rozmieszczonych elementów w przedziale od 7. do 12. włącznie

In [6]:
np.linspace(7, 12, 20)

array([ 7.        ,  7.26315789,  7.52631579,  7.78947368,  8.05263158,
        8.31578947,  8.57894737,  8.84210526,  9.10526316,  9.36842105,
        9.63157895,  9.89473684, 10.15789474, 10.42105263, 10.68421053,
       10.94736842, 11.21052632, 11.47368421, 11.73684211, 12.        ])

6. Utwórz dwuwymiarową tablicę (4x4), której przekątna jest równa [1, 2, 3, 4] i zawiera 0 w innych miejscach

In [7]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

7. Niech x będzie macierzą o następujących wymiarach [10, 10, 3] i niech wszystkie jej elementy będą równe jeden. Następnie przekształć x tak, aby tworzył macierz (2Darray), a rozmiar drugiego wymiaru był równy 150.

In [8]:
x = np.ones((10, 10, 3))
x = x.reshape(2, 150)
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]]


8. Niech x będzie tablicą [[1, 2, 3], [4, 5, 6]]. Przekształć ją na [1 4 2 5 3 6].

In [9]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.transpose(x).flatten()

array([1, 4, 2, 5, 3, 6])

9. Niech X = np.arange(1, 5).reshape((2, 2)) i oblicz wyznacznik X.

In [10]:
X = np.arange(1, 5).reshape((2, 2))
print(X)
np.linalg.det(X)

[[1 2]
 [3 4]]


-2.0000000000000004

10. Zwróć sumę elementów na przekątnej A = np.linspace(2, 16, 16).reshape(4, 4)

In [11]:
A = np.linspace(2, 16, 16).reshape(4, 4)
print(A)
A.diagonal().sum()

[[ 2.          2.93333333  3.86666667  4.8       ]
 [ 5.73333333  6.66666667  7.6         8.53333333]
 [ 9.46666667 10.4        11.33333333 12.26666667]
 [13.2        14.13333333 15.06666667 16.        ]]


36.0

11. Znajdź odwrotność np.array([[1., 2.], [3., 4.]])

In [12]:
b = np.array([[1., 2.], [3., 4.]])
inv_b = np.linalg.inv(b)
inv_b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

12. Dla następujących wektorów,

x = np.array([4, 5, 6, 13])
y = np.array([5, 0, 6, 11])
sprawdź, które elementy x są większe od elementów y

In [13]:
x = np.array([4, 5, 6, 13])
y = np.array([5, 0, 6, 11])
x > y

array([False,  True, False,  True])