Analiza raportów finansowych za pomocą Numpy

In [5]:
import numpy as np
import pandas as pd
from numpy.lib import recfunctions as rfn

In [6]:
dtype = [
    ('Company', 'U10'),
    ('Quarter', 'U10'),
    ('Revenue', 'f8'),
    ('Profit', 'f8'),
    ('Expenses', 'f8')
]

In [7]:
data = np.genfromtxt("..\\dane\\financial_data.csv", delimiter=",", dtype=dtype, names=["Company", "Quarter", "Revenue", "Profit", "Expenses"], skip_header=1)
data = np.ma.filled(data)

Wyznacz kolejne istotne wskaźniki finansowe:
1. Oblicz wskaźniki Profit Margin i Expense Ratio.

In [8]:
profit_margin = np.divide(data["Profit"], data["Revenue"])
profit_margin

array([0.25411902, 0.49585635, 0.12701939, 0.39447472, 0.42071934,
       0.18264432, 0.2061279 , 0.07740442, 0.11843369, 0.39007274,
       0.9145696 , 0.32550471, 0.62980863, 0.09927016, 0.06048223,
       0.13805862])

In [9]:
expense_ratio = np.divide(data["Expenses"], data["Revenue"])
expense_ratio

array([0.74588098, 0.50414365, 0.87298061, 0.60552528, 0.57928066,
       0.81735568, 0.7938721 , 0.92259558, 0.88156631, 0.60992726,
       0.0854304 , 0.67449529, 0.37019137, 0.90072984, 0.93951777,
       0.86194138])

In [10]:
data = rfn.append_fields(names=["Profit Margin", "Expense ratio"], data=[profit_margin, expense_ratio], dtypes=["f8", "f8"], base=data)
data = np.ma.filled(data)
data

array([('Company A', 'Q1', 25795., 6555., 19240., 0.25411902, 0.74588098),
       ('Company A', 'Q2', 10860., 5385.,  5475., 0.49585635, 0.50414365),
       ('Company A', 'Q3', 48158., 6117., 42041., 0.12701939, 0.87298061),
       ('Company A', 'Q4', 21284., 8396., 12888., 0.39447472, 0.60552528),
       ('Company B', 'Q1', 16265., 6843.,  9422., 0.42071934, 0.57928066),
       ('Company B', 'Q2', 26850., 4904., 21946., 0.18264432, 0.81735568),
       ('Company B', 'Q3', 47194., 9728., 37466., 0.2061279 , 0.7938721 ),
       ('Company B', 'Q4', 31962., 2474., 29488., 0.07740442, 0.92259558),
       ('Company C', 'Q1', 26023., 3082., 22941., 0.11843369, 0.88156631),
       ('Company C', 'Q2', 11685., 4558.,  7127., 0.39007274, 0.60992726),
       ('Company C', 'Q3', 10769., 9849.,   920., 0.9145696 , 0.0854304 ),
       ('Company C', 'Q4', 12433., 4047.,  8386., 0.32550471, 0.67449529),
       ('Company D', 'Q1', 15311., 9643.,  5668., 0.62980863, 0.37019137),
       ('Company D', 'Q2'

2. Wyznacz wskaźnik wzrostu przychodu (Revenue Growth).

In [11]:
revenue_growth = np.diff(data["Revenue"], append=0)
revenue_growth

array([-14935.,  37298., -26874.,  -5019.,  10585.,  20344., -15232.,
        -5939., -14338.,   -916.,   1664.,   2878.,  32508.,   1369.,
       -21620., -27568.])

In [12]:
growth_rate = revenue_growth / data["Revenue"]
growth_rate = np.insert(growth_rate, 0, 0)
growth_rate = growth_rate[:-1]
growth_rate

array([ 0.        , -0.57898818,  3.43443831, -0.55803812, -0.23581094,
        0.65078389,  0.75769088, -0.32275289, -0.1858144 , -0.55097414,
       -0.0783911 ,  0.1545176 ,  0.23148074,  2.12317941,  0.02862879,
       -0.4395381 ])

In [13]:
data = rfn.append_fields(names=["Growth Rate"], data=[growth_rate], dtypes=["f8"], base=data)
data = np.ma.filled(data)
data

array([('Company A', 'Q1', 25795., 6555., 19240., 0.25411902, 0.74588098,  0.        ),
       ('Company A', 'Q2', 10860., 5385.,  5475., 0.49585635, 0.50414365, -0.57898818),
       ('Company A', 'Q3', 48158., 6117., 42041., 0.12701939, 0.87298061,  3.43443831),
       ('Company A', 'Q4', 21284., 8396., 12888., 0.39447472, 0.60552528, -0.55803812),
       ('Company B', 'Q1', 16265., 6843.,  9422., 0.42071934, 0.57928066, -0.23581094),
       ('Company B', 'Q2', 26850., 4904., 21946., 0.18264432, 0.81735568,  0.65078389),
       ('Company B', 'Q3', 47194., 9728., 37466., 0.2061279 , 0.7938721 ,  0.75769088),
       ('Company B', 'Q4', 31962., 2474., 29488., 0.07740442, 0.92259558, -0.32275289),
       ('Company C', 'Q1', 26023., 3082., 22941., 0.11843369, 0.88156631, -0.1858144 ),
       ('Company C', 'Q2', 11685., 4558.,  7127., 0.39007274, 0.60992726, -0.55097414),
       ('Company C', 'Q3', 10769., 9849.,   920., 0.9145696 , 0.0854304 , -0.0783911 ),
       ('Company C', 'Q4', 12433

In [14]:
cond = data["Quarter"] != "Q1"
filtered_data = data[cond]
filtered_data

array([('Company A', 'Q2', 10860., 5385.,  5475., 0.49585635, 0.50414365, -0.57898818),
       ('Company A', 'Q3', 48158., 6117., 42041., 0.12701939, 0.87298061,  3.43443831),
       ('Company A', 'Q4', 21284., 8396., 12888., 0.39447472, 0.60552528, -0.55803812),
       ('Company B', 'Q2', 26850., 4904., 21946., 0.18264432, 0.81735568,  0.65078389),
       ('Company B', 'Q3', 47194., 9728., 37466., 0.2061279 , 0.7938721 ,  0.75769088),
       ('Company B', 'Q4', 31962., 2474., 29488., 0.07740442, 0.92259558, -0.32275289),
       ('Company C', 'Q2', 11685., 4558.,  7127., 0.39007274, 0.60992726, -0.55097414),
       ('Company C', 'Q3', 10769., 9849.,   920., 0.9145696 , 0.0854304 , -0.0783911 ),
       ('Company C', 'Q4', 12433., 4047.,  8386., 0.32550471, 0.67449529,  0.1545176 ),
       ('Company D', 'Q2', 47819., 4747., 43072., 0.09927016, 0.90072984,  2.12317941),
       ('Company D', 'Q3', 49188., 2975., 46213., 0.06048223, 0.93951777,  0.02862879),
       ('Company D', 'Q4', 27568

In [15]:
ascending_indices = np.argsort(filtered_data["Growth Rate"])
descending_indices = ascending_indices[::-1]
filtered_data = filtered_data[descending_indices]
filtered_data

array([('Company A', 'Q3', 48158., 6117., 42041., 0.12701939, 0.87298061,  3.43443831),
       ('Company D', 'Q2', 47819., 4747., 43072., 0.09927016, 0.90072984,  2.12317941),
       ('Company B', 'Q3', 47194., 9728., 37466., 0.2061279 , 0.7938721 ,  0.75769088),
       ('Company B', 'Q2', 26850., 4904., 21946., 0.18264432, 0.81735568,  0.65078389),
       ('Company C', 'Q4', 12433., 4047.,  8386., 0.32550471, 0.67449529,  0.1545176 ),
       ('Company D', 'Q3', 49188., 2975., 46213., 0.06048223, 0.93951777,  0.02862879),
       ('Company C', 'Q3', 10769., 9849.,   920., 0.9145696 , 0.0854304 , -0.0783911 ),
       ('Company B', 'Q4', 31962., 2474., 29488., 0.07740442, 0.92259558, -0.32275289),
       ('Company D', 'Q4', 27568., 3806., 23762., 0.13805862, 0.86194138, -0.4395381 ),
       ('Company C', 'Q2', 11685., 4558.,  7127., 0.39007274, 0.60992726, -0.55097414),
       ('Company A', 'Q4', 21284., 8396., 12888., 0.39447472, 0.60552528, -0.55803812),
       ('Company A', 'Q2', 10860

3. Wyznacz percentyl 10% na podstawie wszystkich uzyskanych wyników. 

In [16]:
percentile = np.percentile(filtered_data["Growth Rate"], 10)
percentile

-0.5573317258823791

4. Wyświetl wskaźnik wzrostu (Revenue Growth) jedynie dla firm i kwartałów, w którym były one najbardziej rentowne, tj. przekraczały wynik dla percentyla 10%.

In [17]:
cond2 = filtered_data["Growth Rate"] > percentile
filtered_data = filtered_data[cond2]

In [18]:
filtered_data

array([('Company A', 'Q3', 48158., 6117., 42041., 0.12701939, 0.87298061,  3.43443831),
       ('Company D', 'Q2', 47819., 4747., 43072., 0.09927016, 0.90072984,  2.12317941),
       ('Company B', 'Q3', 47194., 9728., 37466., 0.2061279 , 0.7938721 ,  0.75769088),
       ('Company B', 'Q2', 26850., 4904., 21946., 0.18264432, 0.81735568,  0.65078389),
       ('Company C', 'Q4', 12433., 4047.,  8386., 0.32550471, 0.67449529,  0.1545176 ),
       ('Company D', 'Q3', 49188., 2975., 46213., 0.06048223, 0.93951777,  0.02862879),
       ('Company C', 'Q3', 10769., 9849.,   920., 0.9145696 , 0.0854304 , -0.0783911 ),
       ('Company B', 'Q4', 31962., 2474., 29488., 0.07740442, 0.92259558, -0.32275289),
       ('Company D', 'Q4', 27568., 3806., 23762., 0.13805862, 0.86194138, -0.4395381 ),
       ('Company C', 'Q2', 11685., 4558.,  7127., 0.39007274, 0.60992726, -0.55097414)],
      dtype=[('Company', '<U10'), ('Quarter', '<U10'), ('Revenue', '<f8'), ('Profit', '<f8'), ('Expenses', '<f8'), ('Pr

5. Dla każdej z firm, policz ile razy osiągnęła wynik High-Growth i wyświetl uzyskane wyniki.

In [19]:
unique, counts = np.unique(filtered_data["Company"], return_counts=True)

In [20]:
unique, counts

(array(['Company A', 'Company B', 'Company C', 'Company D'], dtype='<U10'),
 array([1, 3, 3, 3], dtype=int64))

6. Uszereguj firmy w oparciu o kryteria, takie jak ilość kwartałów High-Growth oraz najwyższy wzrost przychodów.

In [21]:
comp_B = data[data["Company"] == "Company B"]
comp_B

array([('Company B', 'Q1', 16265., 6843.,  9422., 0.42071934, 0.57928066, -0.23581094),
       ('Company B', 'Q2', 26850., 4904., 21946., 0.18264432, 0.81735568,  0.65078389),
       ('Company B', 'Q3', 47194., 9728., 37466., 0.2061279 , 0.7938721 ,  0.75769088),
       ('Company B', 'Q4', 31962., 2474., 29488., 0.07740442, 0.92259558, -0.32275289)],
      dtype=[('Company', '<U10'), ('Quarter', '<U10'), ('Revenue', '<f8'), ('Profit', '<f8'), ('Expenses', '<f8'), ('Profit Margin', '<f8'), ('Expense ratio', '<f8'), ('Growth Rate', '<f8')])

In [22]:
avg_B = np.round(np.average(comp_B["Profit Margin"]),2)
avg_B

0.22

In [23]:
comp_C = data[data["Company"] == "Company C"]
comp_C

array([('Company C', 'Q1', 26023., 3082., 22941., 0.11843369, 0.88156631, -0.1858144 ),
       ('Company C', 'Q2', 11685., 4558.,  7127., 0.39007274, 0.60992726, -0.55097414),
       ('Company C', 'Q3', 10769., 9849.,   920., 0.9145696 , 0.0854304 , -0.0783911 ),
       ('Company C', 'Q4', 12433., 4047.,  8386., 0.32550471, 0.67449529,  0.1545176 )],
      dtype=[('Company', '<U10'), ('Quarter', '<U10'), ('Revenue', '<f8'), ('Profit', '<f8'), ('Expenses', '<f8'), ('Profit Margin', '<f8'), ('Expense ratio', '<f8'), ('Growth Rate', '<f8')])

In [24]:
avg_C = np.round(np.average(comp_C["Profit Margin"]),2)
avg_C

0.44

In [25]:
comp_D = data[data["Company"] == "Company D"]
comp_D

array([('Company D', 'Q1', 15311., 9643.,  5668., 0.62980863, 0.37019137,  0.23148074),
       ('Company D', 'Q2', 47819., 4747., 43072., 0.09927016, 0.90072984,  2.12317941),
       ('Company D', 'Q3', 49188., 2975., 46213., 0.06048223, 0.93951777,  0.02862879),
       ('Company D', 'Q4', 27568., 3806., 23762., 0.13805862, 0.86194138, -0.4395381 )],
      dtype=[('Company', '<U10'), ('Quarter', '<U10'), ('Revenue', '<f8'), ('Profit', '<f8'), ('Expenses', '<f8'), ('Profit Margin', '<f8'), ('Expense ratio', '<f8'), ('Growth Rate', '<f8')])

In [26]:
avg_D = np.round(np.average(comp_D["Profit Margin"]),2)
avg_D

0.23

In [27]:
empty = np.zeros(4)
solution = rfn.append_fields(names=["Consistent High-Growth Quarters", "Average Profit Margin"], data=[counts, empty], dtypes=["f8", "f8"], base=unique)
solution = np.ma.filled(solution)
solution = solution[1:]
solution

array([('Company B', 3., 0.), ('Company C', 3., 0.),
       ('Company D', 3., 0.)],
      dtype=[('f0', '<U10'), ('Consistent High-Growth Quarters', '<f8'), ('Average Profit Margin', '<f8')])

In [28]:
solution["Average Profit Margin"][0] = avg_B 
solution["Average Profit Margin"][1] = avg_C
solution["Average Profit Margin"][2] = avg_D
solution

array([('Company B', 3., 0.22), ('Company C', 3., 0.44),
       ('Company D', 3., 0.23)],
      dtype=[('f0', '<U10'), ('Consistent High-Growth Quarters', '<f8'), ('Average Profit Margin', '<f8')])

In [29]:
ascending_indices = np.argsort(solution["Average Profit Margin"])
descending_indices = ascending_indices[::-1]
solution = solution[descending_indices]
solution

array([('Company C', 3., 0.44), ('Company D', 3., 0.23),
       ('Company B', 3., 0.22)],
      dtype=[('f0', '<U10'), ('Consistent High-Growth Quarters', '<f8'), ('Average Profit Margin', '<f8')])

In [30]:
df = pd.DataFrame(solution)
df

f0  Consistent High-Growth Quarters  Average Profit Margin
0  Company C                              3.0                   0.44
1  Company D                              3.0                   0.23
2  Company B                              3.0                   0.22